##
## Makefile for Makefile in /exam//rendu/ex_1
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Sat Apr  7 10:31:25 2012 exam_user
## Last update Sat Apr  7 11:02:02 2012 exam_user
##

CC	=	gcc -o

NAME	=	epur_str

SRC	=	epur_str.c

RM	=	rm -f

all:
	$(CC) $(NAME) $(SRC)

clean:
	$(RM) $(NAME)