##
## Makefile for rev_str in /exam//rendu/ex_3
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Sat Nov 12 10:42:17 2011 exam_user
## Last update Sat Nov 12 10:44:32 2011 exam_user
##

CC = cc

SRC = *.c

OBJ = *.o

NAME = rev_str

RM = rm

all:	compile
	$(CC) -o $(NAME) $(OBJ)

compile:
	$(CC) -c $(SRC)

clean:
	$(RM) $(NAME)