##
## Makefile for minitalk in /home/guillo_e//Documents/working/unix/minitalk
## 
## Made by lyoma guillou
## Login   <guillo_e@epitech.net>
## 
## Started on  Mon Mar  5 17:37:52 2012 lyoma guillou
## Last update Thu Mar 15 18:24:28 2012 lyoma guillou
##

all:
	make -C server
	make -C client

server:
	make -C server

client:
	make -C client

clean:
	make clean -C server
	make clean -C client

fclean:
	make fclean -C server
	make fclean -C client

re:	fclean all
