##
## Makefile for str_capitalize in /exam//rendu/ex_1
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Sat Mar 24 10:02:35 2012 exam_user
## Last update Sat Mar 24 10:16:30 2012 exam_user
##

CC	= gcc -o

OBJ	= str_capitalize

SRC	= str_capitalize.c

RM	= rm -f

all:
	$(CC) $(OBJ) $(SRC)

clean:
	$(RM) $(OBJ)