##
## Makefile for Makefile in /exam//rendu/ex_3
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Thu Nov 25 11:36:53 2010 exam_user
## Last update Thu Nov 25 11:54:56 2010 exam_user
##

SRC = ulstr.c

CC = cc

OPT = -o 

NAME = ulstr

RM = rm

all:
	$(CC) $(OPT) $(NAME) $(SRC)

clean:
	$(RM) $(NAME)