##
## Makefile for ord_alphlong in /exam//rendu/ex_1
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Sat Mar 24 10:02:35 2012 exam_user
## Last update Sat Mar 24 11:50:16 2012 exam_user
##

CC	= 	gcc -o

OBJ	= 	ord_alphlong

SRC	= 	ord_alphlong.c \
		str_funcs.c \
		is_char_type.c

RM	= 	rm -f

all:
	$(CC) $(OBJ) $(SRC)

clean:
	$(RM) $(OBJ)