##
## Makefile for do_op in /exam//rendu/ex_1
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Sat Feb 11 10:38:42 2012 exam_user
## Last update Sat Feb 11 10:57:38 2012 exam_user
##

CC 	=	cc

NAME 	=	do_op

SRC	=	do_op.c

all:
	$(CC) -o $(NAME) $(SRC)