##
## Makefile for  in /exam//rendu/ex_1
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Thu Jun  7 09:18:26 2012 exam_user
## Last update Thu Jun  7 09:50:32 2012 exam_user
##

all:
	touch rev_str
	chmod +x rev_str
	cat rev_str.rb > rev_str
