##
## Makefile for Makefile in /exam//rendu/ex_2
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Fri Mar 11 10:44:00 2011 exam_user
## Last update Fri Mar 11 10:46:53 2011 exam_user
##

CC = cc -o

SRC = *.c

OBJ = str_capitalize

RM = rm

all:
	$(CC) $(OBJ) $(SRC)

clean:
	$(RM) $(OBJ)