##
## Makefile for Makefile in /exam//rendu/ex_2
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Thu Nov 25 10:45:03 2010 exam_user
## Last update Thu Nov 25 11:13:25 2010 exam_user
##

SRC = rotone.c

CC = cc

OPT = -o

NAME = rotone

RM = rm

BCK = *~

BUFF = *#

all:
	$(CC) $(OPT) $(NAME) $(SRC)

clean:
	$(RM) $(NAME)