##
## Makefile for hidenp in /exam//rendu/ex_4
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Sat Jan  7 11:04:47 2012 exam_user
## Last update Sat Jan  7 11:13:27 2012 exam_user
##

CC = cc

SRC = hidenp.c

NAME = hidenp

all:
	$(CC) $(SRC) -o $(NAME)