##
## Makefile for Makefile in /exam//rendu/ex_4
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Sat Nov 13 11:43:40 2010 exam_user
## Last update Sat Nov 13 12:58:49 2010 exam_user
##

SRC = infin_add.c

BIN = infin_add.o

OBJ = infin_add

COMP = $(OBJ) $(BIN)

CC = cc

CFLAG = -c

OFLAG = -o

all :
	$(CC) $(CFLAG) $(SRC)
	$(CC) $(OFLAG) $(COMP)

clean :
	rm $(BIN)
