##
## Makefile for ord_alphlong in /exam//rendu/ex_2
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Mon Mar 28 18:21:00 2011 exam_user
## Last update Mon Mar 28 18:21:16 2011 exam_user
##

all:
	cc -o ord_alphlong *.c