##
## Makefile for colle3 in /home/guillo_e//working/colle/colle3
## 
## Made by lyoma guillou
## Login   <guillo_e@epitech.net>
## 
## Started on  Sat Oct 29 23:38:42 2011 lyoma guillou
## Last update Sat Oct 29 23:45:42 2011 lyoma guillou
##

CCO = cc -o

SRC = *.c

NAME = colle3

LIB = -L./ -lmy

RMF = rm -f

all:
	$(CCO) $(NAME) $(SRC) $(LIB) -ggdb3

clean:
	$(RMF) $(NAME)