##
## Makefile for rev_wstr in /exam//rendu/ex_1
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Sat Feb 11 10:38:42 2012 exam_user
## Last update Sat Feb 11 10:42:27 2012 exam_user
##

CC 	=	cc

NAME 	=	rev_wstr

SRC	=	rev_wstr.c

all:
	$(CC) -o $(NAME) $(SRC)