##
## Makefile for hidenp in /exam//rendu/ex_4
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Sat Oct 29 10:27:59 2011 exam_user
## Last update Sat Oct 29 10:52:43 2011 exam_user
##

CCO = cc -o

NAME = hidenp

SRC = *.c

RMF = rm -f

all:
	$(CCO) $(NAME) $(SRC)

clean:
	$(RMF) $(NAME)