##
## Makefile for Makefile in /exam//rendu/ex_3
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Fri Mar 11 11:07:54 2011 exam_user
## Last update Fri Mar 11 11:08:46 2011 exam_user
##

CC = cc -o

SRC = *.c

OBJ = count_island

RM = rm

all:
	$(CC) $(OBJ) $(SRC)

clean:
	$(RM) $(OBJ)