##
## Makefile for  in /exam//rendu/ex_2
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Sat Mar 10 10:52:46 2012 exam_user
## Last update Sat Mar 10 12:28:48 2012 exam_user
##

CC	= gcc -o

NAME	= str_capitalize

SRC	= str_capitalize.c

RM	= rm -f


all:
	$(CC) $(NAME) $(SRC)

clean:
	$(RM) $(NAME)