##
## Makefile for sort_word in /exam//rendu/ex_1
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Wed Feb 22 17:33:55 2012 exam_user
## Last update Wed Feb 22 19:06:24 2012 exam_user
##

CC = cc

SRC = sort_word.c

OBJ = sort_word

RM = rm

all:
	$(CC) -o $(OBJ) $(SRC)

clean:
	$(RM) $(OBJ)