##
## Makefile for half_str in /exam//rendu/ex_1
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Sat Dec 10 10:44:07 2011 exam_user
## Last update Sat Dec 10 11:04:30 2011 exam_user
##

CC	=	cc

SRC	=	*.c

NAME	=	infin_mult

RM	=	rm -f

all:	
	$(CC) -o $(NAME) $(SRC) 

clean:
	$(RM) $(NAME)