##
## Makefile for do_op in /exam//rendu/ex_1
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Sat Mar 24 10:02:35 2012 exam_user
## Last update Sat Mar 24 10:03:38 2012 exam_user
##

CC	= gcc -o

OBJ	= do_op

SRC	= do_op.c

RM	= rm -f

all:
	$(CC) $(OBJ) $(SRC)

clean:
	$(RM) $(OBJ)