##
## Makefile for makefile in /exam//rendu/ex_1
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Thu Jan 19 10:31:02 2012 exam_user
## Last update Thu Jan 19 10:45:04 2012 exam_user
##

CC	=	cc

NAME	=	my_atoi_base

SRC	=	my_atoi_base.c \
		main.c

RM	=	rm

all:
	$(CC) -o $(NAME) $(SRC) -I.

clean:
	$(RM) $(NAME)