##
## Makefile for Makefile in /exam//rendu/ex_2
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Wed Jan 19 10:48:57 2011 exam_user
## Last update Wed Jan 19 10:50:00 2011 exam_user
##

CC = cc -o

OBJ = hidenp

SRC = hidenp.c

RM = rm

all:
	$(CC) $(OBJ) $(SRC)

clean:
	$(RM) $(OBJ)