##
## Makefile for Makefile in /exam//rendu/ex_1
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Wed Jan 19 10:33:26 2011 exam_user
## Last update Wed Jan 19 10:34:37 2011 exam_user
##

CC = cc -o

OBJ = rotone

SRC = rotone.c

RM = rm

all:
	$(CC) $(OBJ) $(SRC)

clean:
	$(RM) $(OBJ)