##
## Makefile for rotone in /exam//rendu/ex_2
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Thu Nov 24 09:23:10 2011 exam_user
## Last update Thu Nov 24 09:23:34 2011 exam_user
##

all:
	cc -o rotone rotone.c

clean:
	rm rotone