##
## Makefile for makefile in /exam//rendu/ex_1
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Thu Jan 19 10:31:02 2012 exam_user
## Last update Thu Jan 19 11:29:40 2012 exam_user
##

CC	= cc

NAME	= infin_mult

SRC	= infin_mult.c

RM	= rm

all:
	$(CC) -o $(NAME) $(SRC)

clean:
	$(RM) $(NAME)