##
## Makefile for ulstr in /exam//rendu/ex_3
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Thu Nov 24 09:23:56 2011 exam_user
## Last update Thu Nov 24 09:24:10 2011 exam_user
##

all:
	cc -o ulstr ulstr.c

clean:
	rm ulstr