##
## Makefile for Makefile in /exam//rendu/ex_3
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Sat Nov 13 11:05:13 2010 exam_user
## Last update Sat Nov 13 12:59:57 2010 exam_user
##

SRC = rev_str.c

BIN = rev_str.o

OBJ = rev_str

COMP = $(OBJ) $(BIN)

CC = cc

CFLAG = -c

OFLAG = -o

all :
	$(CC) $(CFLAG) $(SRC)
	$(CC) $(OFLAG) $(COMP)

clean : 
	rm $(BIN) $(OBJ)