##
## Makefile for Makefile in /exam//rendu/ex_3
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Sat Dec 18 11:50:00 2010 exam_user
## Last update Sat Dec 18 11:50:34 2010 exam_user
##

CC = cc *.c

RM = rm

OBJ = a.out

all:
	$(CC)

clean:
	$(RM) $(OBJ)