##
## Makefile for magicsquare in /exam//rendu/ex_1
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Wed Feb 22 17:33:55 2012 exam_user
## Last update Wed Feb 22 19:37:04 2012 exam_user
##

CC = cc

SRC = magicsquare.c

OBJ = msquare

RM = rm

all:
	$(CC) -o $(OBJ) $(SRC) -ggdb3

clean:
	$(RM) $(OBJ)