##
## Makefile for corewar in /home/duverd_l/
## 
## Made by louis duverdier
## Login   <duverd_l@epitech.net>
## 
## Started on  Wed Jan 18 14:38:44 2012 louis duverdier
## Last update Wed Jan 18 17:10:45 2012 louis duverdier
##

all:
	make -C asm

clean:
	make clean -C asm

fclean:
	make fclean -C asm

re:	fclean all
