##
## Makefile for str_capitalize in /exam//rendu/ex_2
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Sat Jan  7 11:04:47 2012 exam_user
## Last update Sat Jan  7 11:05:36 2012 exam_user
##

CC = cc

SRC = str_capitalize.c

NAME = str_capitalize

all:
	$(CC) $(SRC) -o $(NAME)