##
## Makefile for colle3 in /home/guillo_e//working/colle
## 
## Made by lyoma guillou
## Login   <guillo_e@epitech.net>
## 
## Started on  Sun Oct 30 00:43:14 2011 lyoma guillou
## Last update Sun Oct 30 01:02:53 2011 lyoma guillou
##

CC = cc

SRC = *.c

BIN = *.o

NAME = colle3

RMF = rm -f

all:	bin
	$(CC) -o $(NAME) $(BIN)

bin:
	$(CC) -c $(SRC)

clean:
	$(RMF) $(NAME)

fclean: clean
	$(RMF) $(BIN)