##
## Makefile for Makefile in /exam//rendu/ex_4
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Thu Jan  6 11:16:05 2011 exam_user
## Last update Thu Jan  6 11:17:13 2011 exam_user
##

CCO = cc -o

OBJ = hidenp

SRC = hidenp.c

RM = rm

all:
	$(CCO) $(OBJ) $(SRC)

clean:
	$(RM) $(OBJ)