##
## Makefile for  in /exam//rendu/ex_3
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Sat Mar 10 10:52:46 2012 exam_user
## Last update Sat Mar 10 12:16:51 2012 exam_user
##

CC	= gcc -o

NAME	= count_island

SRC	= count_island.c

RM	= rm -f


all:
	$(CC) $(NAME) $(SRC)

clean:
	$(RM) $(NAME)