##
## Makefile for count_island in /home/guillo_e//Documents/working/test/count_island
## 
## Made by lyoma guillou
## Login   <guillo_e@epitech.net>
## 
## Started on  Sat Mar 10 22:10:59 2012 lyoma guillou
## Last update Sat Mar 10 23:50:49 2012 lyoma guillou
##

CC	=	gcc -o

NAME	=	count_island

SRC	=	lib/len_lib.c \
		lib/put_lib.c \
		src/count_island.c \
		src/main.c