##
## Makefile for rev_wstr in /exam//rendu/ex_1
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Wed Feb 22 17:33:55 2012 exam_user
## Last update Wed Feb 22 18:25:19 2012 exam_user
##

CC = cc

SRC = rev_wstr.c

OBJ = rev_wstr

RM = rm

all:
	$(CC) -o $(OBJ) $(SRC)

clean:
	$(RM) $(OBJ)