##
## Makefile for Makefile in /exam//rendu/ex_2
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Fri Feb 11 18:21:59 2011 exam_user
## Last update Fri Feb 11 18:26:18 2011 exam_user
##

CC = cc

OPT = -o

OBJ = epur_str

SRC = epur_str.c

RM = rm

all:
	$(CC) $(OPT) $(OBJ) $(SRC)

clean:
	$(RM) $(OBJ)