##
## Makefile for rotone in /exam//rendu/ex_1
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Mon Mar 28 18:01:02 2011 exam_user
## Last update Mon Mar 28 18:01:17 2011 exam_user
##

all:
	cc -o rotone *.c