##
## Makefile for  in /exam//rendu/ex_1
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Thu Jun  7 09:18:26 2012 exam_user
## Last update Thu Jun  7 09:28:26 2012 exam_user
##

CC 	= gcc

NAME	= rotone

SRC	= rotone.c

OBJ	= $(SRC:.c=.o)

RM	= rm -f

all:
	$(CC) -o $(NAME) $(SRC)