##
## Makefile for minitalk in /home/guillo_e//Documents/working/unix/minitalk
## 
## Made by lyoma guillou
## Login   <guillo_e@epitech.net>
## 
## Started on  Mon Mar  5 17:37:52 2012 lyoma guillou
## Last update Mon Mar  5 17:38:29 2012 lyoma guillou
##

all:
	make -C server

clean:
	make clean -C server

fclean:
	make fclean -C server

re:	fclean all
