##
## Makefile for Makefile in /exam//rendu/ex_2
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Sat Dec 18 11:47:02 2010 exam_user
## Last update Sat Dec 18 13:07:01 2010 exam_user
##

CC = cc -o 

CF = *.c

RM = rm

NAME = epur_str

all:
	$(CC) $(NAME) $(CF)

clean:
	$(RM) $(NAME)