##
## Makefile for Makefile in /exam//rendu/ex_3
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Thu Jan  6 11:02:21 2011 exam_user
## Last update Thu Jan  6 11:03:02 2011 exam_user
##

CCO = cc -o

OBJ = rotone

SRC = rotone.c

RM = rm

all:
	cc -o rotone rotone.c

clean:
	rm rotone