##
## Makefile for epur_str in /exam//rendu/ex_5
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Sat Oct 29 10:29:11 2011 exam_user
## Last update Sat Oct 29 10:52:29 2011 exam_user
##

CCO = cc -o

NAME = epur_str

SRC = *.c

RMF = rm -f

all:
	$(CCO) $(NAME) $(SRC)

clean:
	$(RMF) $(NAME)