##
## Makefile for  in /exam//rendu/ex_4
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Sat Mar 10 10:52:46 2012 exam_user
## Last update Sat Mar 10 12:18:38 2012 exam_user
##

CC	= gcc -o

NAME	= common_str

SRC	= common_str.c

RM	= rm -f


all:
	$(CC) $(NAME) $(SRC)

clean:
	$(RM) $(NAME)