##
## Makefile for infin_mult in /exam//rendu/ex_4
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Thu Nov 24 10:06:50 2011 exam_user
## Last update Thu Nov 24 11:49:52 2011 exam_user
##

CC	=	cc

NAME	=	infin_mult

SRC	=	string_funcs.c \
		converters.c \
		mult_funcs.c \
		infin_mult.c

INC	=	-I./

RM	=	rm

all:
	$(CC) -o $(NAME) $(SRC) $(INC)

clean:
	$(RM) $(NAME)