##
## Makefile for corewar in /home/duverd_l/
## 
## Made by louis duverdier
## Login   <duverd_l@epitech.net>
## 
## Started on  Wed Jan 18 14:38:44 2012 louis duverdier
## Last update Thu Mar  8 14:54:40 2012 lyoma guillou
##

all:
	make -C kill
	make -C signal

clean:
	make clean -C kill
	make clean -C signal

fclean:
	make fclean -C kill
	make fclean -C signal

re:	fclean all
