##
## Makefile for Makefile in /exam//rendu/ex_4
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Fri Feb 11 18:49:30 2011 exam_user
## Last update Fri Feb 11 18:50:22 2011 exam_user
##

CC = cc

OPT = -o

OBJ = rotone

SRC = rotone.c

RM = rm

all:
	$(CC) $(OPT) $(OBJ) $(SRC)

clean:
	$(RM) $(OBJ)