##
## Makefile for Makefile in /exam//rendu/ex_1
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Mon Feb 21 18:02:39 2011 exam_user
## Last update Mon Feb 21 18:26:58 2011 exam_user
##

CC = cc -o

OBJ = rev_wstr

SRC = *.c

RM = rm

all:
	$(CC) $(OBJ) $(SRC)
clean:
	$(RM) $(OBJ)