##
## Makefile for count_island in /exam//rendu/ex_1
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Sat Feb 11 10:38:42 2012 exam_user
## Last update Sat Feb 11 13:12:26 2012 exam_user
##

CC 	=	cc

NAME 	=	count_island

SRC	=	count_island.c

all:
	$(CC) -o $(NAME) $(SRC)

debug:
	$(CC) -o $(NAME) $(SRC) -ggdb3