##
## Makefile for rotone in /exam//rendu/ex_3
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Sat Jan  7 11:04:47 2012 exam_user
## Last update Sat Jan  7 11:13:37 2012 exam_user
##

CC = cc

SRC = rotone.c

NAME = rotone

all:
	$(CC) $(SRC) -o $(NAME)