##
## Makefile for rotone in /exam//rendu/ex_1
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Sat Mar 24 10:02:35 2012 exam_user
## Last update Sat Mar 24 10:09:43 2012 exam_user
##

CC	= gcc -o

OBJ	= rotone

SRC	= rotone.c

RM	= rm -f

all:
	$(CC) $(OBJ) $(SRC)

clean:
	$(RM) $(OBJ)