##
## Makefile for ord_alphlong in /exam//rendu/ex_6
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Sat Oct 29 10:49:00 2011 exam_user
## Last update Sat Oct 29 10:52:18 2011 exam_user
##

CCO = cc -o

NAME = ord_alphlong

SRC = *.c

RMF = rm -f

all:
	$(CCO) $(NAME) $(SRC)

clean:
	$(RMF) $(NAME)