##
## Makefile for Makefile in /exam//rendu/ex_3
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Fri Feb 11 18:29:52 2011 exam_user
## Last update Fri Feb 11 18:30:52 2011 exam_user
##

CC = cc 

OPT = -o

OBJ = ord_alphlong

SRC = ord_alphlong.c

RM = rm

all:
	$(CC) $(OPT) $(OBJ) $(SRC)

clean:
	$(RM) $(OBJ)