##
## Makefile for pi in /home/guillo_e//Documents/working/colles/colle1
## 
## Made by lyoma guillou
## Login   <guillo_e@epitech.net>
## 
## Started on  Mon Apr 16 19:05:40 2012 lyoma guillou
## Last update Mon Apr 16 19:14:55 2012 lyoma guillou
##

CC 	= 	gcc

NAME	=	pi

SRC 	= 	src/main.c	\

RM	=	rm -f

CFLAGS 	=	-W -Wall -Wextra -pedantic -Iinclude

all:
	$(CC) -o $(NAME) $(SRC) $(CFLAGS)

clean:
	$(RM) src/*.o

fclean:	clean
	$(RM) $(NAME)