##
## Makefile for rstr_capitalizer in /exam//rendu/ex_1
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Fri Apr 20 09:32:11 2012 exam_user
## Last update Fri Apr 20 09:33:31 2012 exam_user
##

CC	=	gcc
SRC	=	rstr_capitalizer.c
NAME	=	rstr_capitalizer
RM	=	rm -f

all:
	$(CC) -o $(NAME) $(SRC)

clean:
	$(RM) *.o

fclean:	clean
	$(RM) $(NAME)