##
## Makefile for Makefile in /exam//rendu/ex_2
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Thu Jan  6 10:43:43 2011 exam_user
## Last update Thu Jan  6 10:45:24 2011 exam_user
##

CCO = cc -o

OBJ = str_capitalize

SRC = str_capitalize.c

RM = rm

all:
	$(CCO) $(OBJ) $(SRC)

clean:
	rm $(OBJ)