##
## Makefile for half_str in /exam//rendu/ex_1
## 
## Made by exam_user
## Login   <guillo_e@epitech.net>
## 
## Started on  Sat Feb 11 10:38:42 2012 exam_user
## Last update Sat Feb 11 10:39:55 2012 exam_user
##

CC 	=	cc

NAME 	=	half_str

SRC	=	half_str.c

all:
	$(CC) -o $(NAME) $(SRC)